version: '3.8'
services:
  mysql:
    image: mysql:8.0.33
    container_name: kream-mysql
    restart: always
    ports:
      - '33061:3306'
    environment:
      MYSQL_USER: kream
      MYSQL_PASSWORD: kream
      MYSQL_DATABASE: kream
      MYSQL_ROOT_PASSWORD: kream
      TZ: 'Asia/Seoul'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysqldb:/var/lib/mysql

  redis:
    image: redis:6.2.6
    container_name: kream-redis
    command: redis-server --port 6379
    restart: always
    ports:
      - "63792:6379"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: kream
      MONGO_INITDB_ROOT_USERNAME: kream
      MONGO_INITDB_ROOT_PASSWORD: kream
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.3.0
#    hostname: zookeeper
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#
#  kafka:
#    image: confluentinc/cp-kafka:7.3.0
#    hostname: kafka
#    container_name: kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
#
#  schema-registry:
#    image: confluentinc/cp-schema-registry:7.3.0
#    hostname: schema-registry
#    container_name: schema-registry
#    depends_on:
#      - zookeeper
#      - kafka
#    ports:
#      - "8081:8081"
#    environment:
#      SCHEMA_REGISTRY_HOST_NAME: schema-registry
#      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:29092"
#      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
#
#  control-center:
#    image: confluentinc/cp-enterprise-control-center:7.3.0
#    hostname: control-center
#    container_name: control-center
#    depends_on:
#      - kafka
#      - schema-registry
#    ports:
#      - "9021:9021"
#    environment:
#      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
#      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
#      CONTROL_CENTER_REPLICATION_FACTOR: 1
#      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
#      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
#      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
#      PORT: 9021

volumes:
  mysqldb:
  mongodb:
