spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:33061/kream?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      username: kream
      password: kream
      pool-name: 'read-write-pool'
      driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:33061/kream?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    user: kream
    password: kream
    locations: classpath:db/migration
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 63792
    mongodb:
      uri: mongodb://kream:kream@localhost:27017/kream?authSource=admin
      database: kream
  kafka:
    topic:
      bidding-created: kream.bidding.created
      bidding-completed: kream.bidding.completed
